"""RENAME about_me bio

Revision ID: e2fdbdfa2e26
Revises: fa197d66957b
Create Date: 2025-07-19 01:33:19.459128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fdbdfa2e26'
down_revision = 'fa197d66957b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=140), nullable=True))
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
